# Generated by Django 4.1.1 on 2022-10-09 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autores',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='editoriales',
            fields=[
                ('id_editorial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='libros',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('edicion', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('paginas', models.IntegerField()),
                ('volumen', models.IntegerField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.autores')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.editoriales')),
            ],
        ),
    ]
