# Generated by Django 4.1.1 on 2022-10-16 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='nombre',
        ),
        migrations.AddField(
            model_name='libros',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='autores',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='editoriales',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='anio',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.autores', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='edicion',
            field=models.IntegerField(verbose_name='Edicion'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.editoriales', verbose_name='Editorial'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='paginas',
            field=models.IntegerField(verbose_name='Numero de paginas'),
        ),
        migrations.AlterField(
            model_name='libros',
            name='volumen',
            field=models.IntegerField(verbose_name='Volumen'),
        ),
    ]
