# Generated by Django 4.1.1 on 2022-10-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_remove_libros_nombre_libros_titulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
