# Generated by Django 4.1.1 on 2022-10-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_lectores_sucursales_prestamos_empleados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectores',
            name='no_tarjeta',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Número de tarjeta'),
        ),
    ]
