# Generated by Django 4.1.1 on 2022-10-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_alter_lectores_no_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copias_libros',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
