# Generated by Django 4.1.1 on 2022-11-12 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_alter_copias_libros_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='id_empleado',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='sueldo',
            field=models.FloatField(verbose_name='Sueldo'),
        ),
        migrations.CreateModel(
            name='administradores',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('nom_usuario', models.CharField(max_length=20, verbose_name='Nombre de usuario')),
                ('contra', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.empleados', verbose_name='Empleado')),
            ],
        ),
    ]
