# Generated by Django 4.1.1 on 2022-11-26 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_alter_empleados_id_empleado_alter_empleados_sueldo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamos',
            name='id_libro',
        ),
        migrations.CreateModel(
            name='libro_prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.libros', verbose_name='Libro')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.prestamos', verbose_name='id_prestamo')),
            ],
        ),
    ]
