# Generated by Django 4.1.1 on 2022-11-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_remove_prestamos_id_libro_libro_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='estado',
            field=models.CharField(default='pendiente', max_length=100, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
