# Generated by Django 4.1.1 on 2022-11-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_prestamos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectores',
            name='no_tarjeta',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Número de tarjeta'),
        ),
    ]
