# Generated by Django 4.1.1 on 2022-11-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_alter_lectores_no_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='estado',
            field=models.CharField(max_length=100, null=True, verbose_name='Estado'),
        ),
    ]
